# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-07 03:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DETAILS', '0006_auto_20180606_0419'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('faculty', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='studentmarks',
            name='subject',
            field=models.ForeignKey(db_column=b'name', on_delete=django.db.models.deletion.CASCADE, related_name='all_names', to='DETAILS.Subject', to_field=b'name'),
        ),
        migrations.DeleteModel(
            name='Subjects',
        ),
    ]
