# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-29 07:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('squares', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='squares',
            new_name='square',
        ),
        migrations.RenameField(
            model_name='square',
            old_name='square',
            new_name='sqr',
        ),
    ]
