# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-05 11:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DETAILS', '0003_auto_20180605_0543'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='DETAILS.StudentMarks')),
            ],
        ),
        migrations.DeleteModel(
            name='SubjectFaculty',
        ),
    ]
