# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-06 04:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DETAILS', '0005_auto_20180606_0340'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='subject',
            name='subject',
        ),
        migrations.AlterField(
            model_name='studentmarks',
            name='subject',
            field=models.ForeignKey(db_column='subject', on_delete=django.db.models.deletion.CASCADE, related_name='all_subjects', to='DETAILS.Subjects', to_field='subject'),
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
